// Code generated by goctl. DO NOT EDIT!
// Source: carousel.proto

package server

import (
	"context"

	"newbee-mall-gozero/service/carousel/rpc/carousel"
	"newbee-mall-gozero/service/carousel/rpc/internal/logic"
	"newbee-mall-gozero/service/carousel/rpc/internal/svc"
)

type CarouselServer struct {
	svcCtx *svc.ServiceContext
	carousel.UnimplementedCarouselServer
}

func NewCarouselServer(svcCtx *svc.ServiceContext) *CarouselServer {
	return &CarouselServer{
		svcCtx: svcCtx,
	}
}

func (s *CarouselServer) GetCarouselsForIndex(ctx context.Context, in *carousel.GetCarouselsForIndexRequest) (*carousel.GetCarouselsForIndexResponse, error) {
	l := logic.NewGetCarouselsForIndexLogic(ctx, s.svcCtx)
	return l.GetCarouselsForIndex(in)
}

func (s *CarouselServer) AddCarousel(ctx context.Context, in *carousel.AddCarouselRequest) (*carousel.EmptyResponse, error) {
	l := logic.NewAddCarouselLogic(ctx, s.svcCtx)
	return l.AddCarousel(in)
}

func (s *CarouselServer) UpdateCarousel(ctx context.Context, in *carousel.UpdateCarouselRequest) (*carousel.EmptyResponse, error) {
	l := logic.NewUpdateCarouselLogic(ctx, s.svcCtx)
	return l.UpdateCarousel(in)
}

func (s *CarouselServer) DeleteCarousel(ctx context.Context, in *carousel.DeleteCarouselRequest) (*carousel.EmptyResponse, error) {
	l := logic.NewDeleteCarouselLogic(ctx, s.svcCtx)
	return l.DeleteCarousel(in)
}

func (s *CarouselServer) GetCarousel(ctx context.Context, in *carousel.GetCarouselRequest) (*carousel.GetCarouselResponse, error) {
	l := logic.NewGetCarouselLogic(ctx, s.svcCtx)
	return l.GetCarousel(in)
}

func (s *CarouselServer) GetCarouselList(ctx context.Context, in *carousel.GetCarouselListRequest) (*carousel.GetCarouselListResponse, error) {
	l := logic.NewGetCarouselListLogic(ctx, s.svcCtx)
	return l.GetCarouselList(in)
}
