// Code generated by goctl. DO NOT EDIT!
// Source: indexconfig.proto

package server

import (
	"context"

	"newbee-mall-gozero/service/index_config/rpc/indexconfig"
	"newbee-mall-gozero/service/index_config/rpc/internal/logic"
	"newbee-mall-gozero/service/index_config/rpc/internal/svc"
)

type IndexconfigServer struct {
	svcCtx *svc.ServiceContext
	indexconfig.UnimplementedIndexconfigServer
}

func NewIndexconfigServer(svcCtx *svc.ServiceContext) *IndexconfigServer {
	return &IndexconfigServer{
		svcCtx: svcCtx,
	}
}

func (s *IndexconfigServer) GetConfigForIndex(ctx context.Context, in *indexconfig.GetConfigForIndexRequest) (*indexconfig.GetConfigForIndexResponse, error) {
	l := logic.NewGetConfigForIndexLogic(ctx, s.svcCtx)
	return l.GetConfigForIndex(in)
}

func (s *IndexconfigServer) AddConfig(ctx context.Context, in *indexconfig.AddConfigRequest) (*indexconfig.EmptyResponse, error) {
	l := logic.NewAddConfigLogic(ctx, s.svcCtx)
	return l.AddConfig(in)
}

func (s *IndexconfigServer) UpdateConfig(ctx context.Context, in *indexconfig.UpdateConfigRequest) (*indexconfig.EmptyResponse, error) {
	l := logic.NewUpdateConfigLogic(ctx, s.svcCtx)
	return l.UpdateConfig(in)
}

func (s *IndexconfigServer) DeleteConfig(ctx context.Context, in *indexconfig.DeleteConfigRequest) (*indexconfig.EmptyResponse, error) {
	l := logic.NewDeleteConfigLogic(ctx, s.svcCtx)
	return l.DeleteConfig(in)
}

func (s *IndexconfigServer) GetConfig(ctx context.Context, in *indexconfig.GetConfigRequest) (*indexconfig.GetConfigResponse, error) {
	l := logic.NewGetConfigLogic(ctx, s.svcCtx)
	return l.GetConfig(in)
}

func (s *IndexconfigServer) GetConfigList(ctx context.Context, in *indexconfig.GetConfigListRequest) (*indexconfig.GetConfigListResponse, error) {
	l := logic.NewGetConfigListLogic(ctx, s.svcCtx)
	return l.GetConfigList(in)
}
