// Code generated by goctl. DO NOT EDIT.
package types

type ThirdLevelCategoryVO struct {
	CategoryId    int64  `json:"categoryId"`
	CategoryLevel int64  `json:"categoryLevel"`
	CategoryName  string `json:"categoryName"`
}

type SecondLevelCategoryVO struct {
	CategoryId            int64                  `json:"categoryId"`
	ParentId              int64                  `json:"parentId"`
	CategoryLevel         int64                  `json:"categoryLevel"`
	CategoryName          string                 `json:"categoryName"`
	ThirdLevelCategoryVOS []ThirdLevelCategoryVO `json:"thirdLevelCategoryVOS"`
}

type GetCategoriesForIndexResponse struct {
	CategoryId             int                     `json:"categoryId"`
	CategoryLevel          int64                   `json:"categoryLevel"`
	CategoryName           string                  `json:"categoryName"`
	SecondLevelCategoryVOS []SecondLevelCategoryVO `json:"secondLevelCategoryVOS"`
}

type Response struct {
	ResultCode int64       `json:"resultCode"`
	Msg        string      `json:"msg"`
	Data       interface{} `json:"data"`
}
