// Code generated by goctl. DO NOT EDIT!
// Source: shoppingcart.proto

package shoppingcart

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Shoppingcart interface {
		AddCartItem(ctx context.Context, in *AddCartItemRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		DeleteCartItem(ctx context.Context, in *DeleteCartItemRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		GetCartList(ctx context.Context, in *GetCartListRequest, opts ...grpc.CallOption) (*GetCartListResponse, error)
		GetCartItems(ctx context.Context, in *GetCartItemsRequest, opts ...grpc.CallOption) (*GetCartItemsResponse, error)
	}

	defaultShoppingcart struct {
		cli zrpc.Client
	}
)

func NewShoppingcart(cli zrpc.Client) Shoppingcart {
	return &defaultShoppingcart{
		cli: cli,
	}
}

func (m *defaultShoppingcart) AddCartItem(ctx context.Context, in *AddCartItemRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := NewShoppingcartClient(m.cli.Conn())
	return client.AddCartItem(ctx, in, opts...)
}

func (m *defaultShoppingcart) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := NewShoppingcartClient(m.cli.Conn())
	return client.UpdateCartItem(ctx, in, opts...)
}

func (m *defaultShoppingcart) DeleteCartItem(ctx context.Context, in *DeleteCartItemRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := NewShoppingcartClient(m.cli.Conn())
	return client.DeleteCartItem(ctx, in, opts...)
}

func (m *defaultShoppingcart) GetCartList(ctx context.Context, in *GetCartListRequest, opts ...grpc.CallOption) (*GetCartListResponse, error) {
	client := NewShoppingcartClient(m.cli.Conn())
	return client.GetCartList(ctx, in, opts...)
}

func (m *defaultShoppingcart) GetCartItems(ctx context.Context, in *GetCartItemsRequest, opts ...grpc.CallOption) (*GetCartItemsResponse, error) {
	client := NewShoppingcartClient(m.cli.Conn())
	return client.GetCartItems(ctx, in, opts...)
}
