// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"newbee-mall-gozero/service/goods_category/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: GetCategoriesHandler(serverCtx),
			},
		},
	)
}
