// Code generated by goctl. DO NOT EDIT.
package types

type Admin struct {
	AdminUserId   int64  `json:"adminUserId"`
	LoginUserName string `json:"loginUserName"`
	LoginPassword string `json:"loginPassword"`
	NickName      string `json:"nickName"`
	Locked        int64  `json:"locked"`
}

type AdminLoginRequest struct {
	UserName    string `json:"userName"`
	PasswordMd5 string `json:"passwordMd5"`
}

type AdminLoginResponse struct {
	Token string `json:"token"`
}

type UpdateAdminNameRequest struct {
	Token         string `header:"token"`
	LoginUserName string `json:"loginUserName"`
	NickName      string `json:"nickName"`
}

type UpdateAdminPwdRequest struct {
	Token            string `header:"token"`
	OriginalPassword string `json:"originalPassword"`
	NewPassword      string `json:"newPassword"`
}

type GetAdminProfileRequest struct {
	Token string `header:"token"`
}

type GetAdminProfileResponse struct {
	Admin Admin `json:"admin"`
}

type GetUserListRequest struct {
	PageNumber int64 `json:"pageNumber"` // 页码
	PageSize   int64 `json:"pageSize"`   // 每页大小
}

type GetUserListResponse struct {
	List       interface{} `json:"list"`
	TotalCount int64       `json:"totalCount"`
	TotalPage  int64       `json:"totalPage"`
	CurrPage   int64       `json:"currPage"`
	PageSize   int64       `json:"pageSize"`
}

type LockUserRequest struct {
	Ids        []int64 `json:"ids"`
	LockStatus int64   `path:"lockStatus"`
}

type LogoutRequest struct {
	Token string `header:"token"`
}

type Response struct {
	ResultCode int         `json:"resultCode"`
	Msg        string      `json:"message"`
	Data       interface{} `json:"data"`
}
