// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTokenFieldNames          = builder.RawFieldNames(&UserToken{})
	userTokenRows                = strings.Join(userTokenFieldNames, ",")
	userTokenRowsExpectAutoSet   = strings.Join(stringx.Remove(userTokenFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userTokenRowsWithPlaceHolder = strings.Join(stringx.Remove(userTokenFieldNames, "`user_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserTokenUserIdPrefix = "cache:userToken:userId:"
	cacheUserTokenTokenPrefix  = "cache:userToken:token:"
)

type (
	userTokenModel interface {
		Insert(ctx context.Context, data *UserToken) (sql.Result, error)
		FindOne(ctx context.Context, userId int64) (*UserToken, error)
		FindOneByToken(ctx context.Context, token string) (*UserToken, error)
		Update(ctx context.Context, data *UserToken) error
		Delete(ctx context.Context, userId int64) error
	}

	defaultUserTokenModel struct {
		sqlc.CachedConn
		table string
	}

	UserToken struct {
		UserId     int64     `db:"user_id"`     // 用户主键id
		Token      string    `db:"token"`       // token值(32位字符串)
		UpdateTime time.Time `db:"update_time"` // 修改时间
		ExpireTime time.Time `db:"expire_time"` // token过期时间
	}
)

func newUserTokenModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserTokenModel {
	return &defaultUserTokenModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_token`",
	}
}

func (m *defaultUserTokenModel) Delete(ctx context.Context, userId int64) error {
	data, err := m.FindOne(ctx, userId)
	if err != nil {
		return err
	}

	userTokenTokenKey := fmt.Sprintf("%s%v", cacheUserTokenTokenPrefix, data.Token)
	userTokenUserIdKey := fmt.Sprintf("%s%v", cacheUserTokenUserIdPrefix, userId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, userId)
	}, userTokenTokenKey, userTokenUserIdKey)
	return err
}

func (m *defaultUserTokenModel) FindOne(ctx context.Context, userId int64) (*UserToken, error) {
	userTokenUserIdKey := fmt.Sprintf("%s%v", cacheUserTokenUserIdPrefix, userId)
	var resp UserToken
	err := m.QueryRowCtx(ctx, &resp, userTokenUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userTokenRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTokenModel) FindOneByToken(ctx context.Context, token string) (*UserToken, error) {
	userTokenTokenKey := fmt.Sprintf("%s%v", cacheUserTokenTokenPrefix, token)
	var resp UserToken
	err := m.QueryRowIndexCtx(ctx, &resp, userTokenTokenKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `token` = ? limit 1", userTokenRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, token); err != nil {
			return nil, err
		}
		return resp.UserId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTokenModel) Insert(ctx context.Context, data *UserToken) (sql.Result, error) {
	userTokenTokenKey := fmt.Sprintf("%s%v", cacheUserTokenTokenPrefix, data.Token)
	userTokenUserIdKey := fmt.Sprintf("%s%v", cacheUserTokenUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userTokenRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Token, data.ExpireTime)
	}, userTokenTokenKey, userTokenUserIdKey)
	return ret, err
}

func (m *defaultUserTokenModel) Update(ctx context.Context, newData *UserToken) error {
	data, err := m.FindOne(ctx, newData.UserId)
	if err != nil {
		return err
	}

	userTokenTokenKey := fmt.Sprintf("%s%v", cacheUserTokenTokenPrefix, data.Token)
	userTokenUserIdKey := fmt.Sprintf("%s%v", cacheUserTokenUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userTokenRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Token, newData.ExpireTime, newData.UserId)
	}, userTokenTokenKey, userTokenUserIdKey)
	return err
}

func (m *defaultUserTokenModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserTokenUserIdPrefix, primary)
}

func (m *defaultUserTokenModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userTokenRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserTokenModel) tableName() string {
	return m.table
}
