// Code generated by goctl. DO NOT EDIT.
package types

type SearchGoodsRequest struct {
	GoodsCategoryId int64  `form:"goodsCategoryId"`
	PageNumber      int64  `form:"pageNumber"`
	Keyword         string `form:"keyword"`
	OrderBy         string `form:"orderBy"`
}

type SearchGoodsResponse struct {
	List       interface{} `json:"list"`
	TotalCount int64       `json:"totalCount"`
	TotalPage  int64       `json:"totalPage"`
	CurrPage   int64       `json:"currPage"`
	PageSize   int64       `json:"pageSize"`
}

type Response struct {
	ResultCode int64       `json:"resultCode"`
	Msg        string      `json:"msg"`
	Data       interface{} `json:"data"`
}
