// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: admintoken.proto

package admintoken

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdmintokenClient is the client API for Admintoken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdmintokenClient interface {
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	GetExistToken(ctx context.Context, in *GetExistTokenRequest, opts ...grpc.CallOption) (*GetExistTokenResponse, error)
	DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*DeleteTokenResponse, error)
}

type admintokenClient struct {
	cc grpc.ClientConnInterface
}

func NewAdmintokenClient(cc grpc.ClientConnInterface) AdmintokenClient {
	return &admintokenClient{cc}
}

func (c *admintokenClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, "/admintoken.admintoken/generateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admintokenClient) GetExistToken(ctx context.Context, in *GetExistTokenRequest, opts ...grpc.CallOption) (*GetExistTokenResponse, error) {
	out := new(GetExistTokenResponse)
	err := c.cc.Invoke(ctx, "/admintoken.admintoken/getExistToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admintokenClient) DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*DeleteTokenResponse, error) {
	out := new(DeleteTokenResponse)
	err := c.cc.Invoke(ctx, "/admintoken.admintoken/deleteToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmintokenServer is the server API for Admintoken service.
// All implementations must embed UnimplementedAdmintokenServer
// for forward compatibility
type AdmintokenServer interface {
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	GetExistToken(context.Context, *GetExistTokenRequest) (*GetExistTokenResponse, error)
	DeleteToken(context.Context, *DeleteTokenRequest) (*DeleteTokenResponse, error)
	mustEmbedUnimplementedAdmintokenServer()
}

// UnimplementedAdmintokenServer must be embedded to have forward compatible implementations.
type UnimplementedAdmintokenServer struct {
}

func (UnimplementedAdmintokenServer) GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedAdmintokenServer) GetExistToken(context.Context, *GetExistTokenRequest) (*GetExistTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExistToken not implemented")
}
func (UnimplementedAdmintokenServer) DeleteToken(context.Context, *DeleteTokenRequest) (*DeleteTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToken not implemented")
}
func (UnimplementedAdmintokenServer) mustEmbedUnimplementedAdmintokenServer() {}

// UnsafeAdmintokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdmintokenServer will
// result in compilation errors.
type UnsafeAdmintokenServer interface {
	mustEmbedUnimplementedAdmintokenServer()
}

func RegisterAdmintokenServer(s grpc.ServiceRegistrar, srv AdmintokenServer) {
	s.RegisterService(&Admintoken_ServiceDesc, srv)
}

func _Admintoken_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmintokenServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admintoken.admintoken/generateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmintokenServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admintoken_GetExistToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExistTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmintokenServer).GetExistToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admintoken.admintoken/getExistToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmintokenServer).GetExistToken(ctx, req.(*GetExistTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admintoken_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmintokenServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admintoken.admintoken/deleteToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmintokenServer).DeleteToken(ctx, req.(*DeleteTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admintoken_ServiceDesc is the grpc.ServiceDesc for Admintoken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admintoken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admintoken.admintoken",
	HandlerType: (*AdmintokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "generateToken",
			Handler:    _Admintoken_GenerateToken_Handler,
		},
		{
			MethodName: "getExistToken",
			Handler:    _Admintoken_GetExistToken_Handler,
		},
		{
			MethodName: "deleteToken",
			Handler:    _Admintoken_DeleteToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admintoken.proto",
}
