// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"newbee-mall-gozero/service/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: AdminLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminJwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/profile",
					Handler: GetAdminProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/name",
					Handler: UpdateAdminNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/password",
					Handler: UpdateAdminPwdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users",
					Handler: GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/users/:lockStatus",
					Handler: LockUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/logout",
					Handler: AdminLogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/goods",
					Handler: AddGoodsInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/goods",
					Handler: UpdateGoodsInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/goods/status/:status",
					Handler: AlterGoodsStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/goods/delete",
					Handler: DeleteGoodsInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/goods/:id",
					Handler: GetGoodsInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/goods/list",
					Handler: GetGoodsListHandler(serverCtx),
				},
			}...,
		),
	)
}
