// Code generated by goctl. DO NOT EDIT.
package types

type Carousel struct {
	CarouselUrl string `json:"carouselUrl"`
	RedirectUrl string `json:"redirectUrl"`
}

type IndexGoods struct {
	GoodsId       int64  `json:"goodsId"`
	GoodsName     string `json:"goodsName"`
	GoodsIntro    string `json:"goodsIntro"`
	GoodsCoverImg string `json:"goodsCoverImg"`
	SellingPrice  int64  `json:"sellingPrice"`
	Tag           string `json:"tag"`
}

type GetIndexInfoResponse struct {
	Carousels      []*Carousel   `json:"carousels"`
	HotGoods       []*IndexGoods `json:"hotGoods"`
	NewGoods       []*IndexGoods `json:"newGoods"`
	RecommendGoods []*IndexGoods `json:"recommendGoods"`
}

type Response struct {
	ResultCode int64       `json:"resultCode"`
	Msg        string      `json:"msg"`
	Data       interface{} `json:"data"`
}
