// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	LoginName   string `json:"loginName"`
	PasswordMd5 string `json:"passwordMd5"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type RegisterRequest struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type UpdateUserInfoRequest struct {
	Token         string `header:"token"`
	NickName      string `json:"nickName"`
	PasswordMd5   string `json:"passwordMd5"`
	IntroduceSign string `json:"introduceSign"`
}

type GetUserInfoRequest struct {
	Token string `header:"token"`
}

type GetUserInfoResponse struct {
	NickName      string `json:"nickName"`
	LoginName     string `json:"loginName"`
	IntroduceSign string `json:"introduceSign"`
}

type LogoutRequest struct {
	Token string `header:"token"`
}

type GetGoodsDetailRequest struct {
	Id int64 `path:"id"`
}

type GetGoodsDetailResponse struct {
	GoodsId            int64    `json:"goodsId"`
	GoodsName          string   `json:"goodsName"`
	GoodsIntro         string   `json:"goodsIntro"`
	GoodsCoverImg      string   `json:"goodsCoverImg"`
	SellingPrice       int64    `json:"sellingPrice"`
	GoodsDetailContent string   `json:"goodsDetailContent"`
	OriginalPrice      int64    `json:"originalPrice"`
	Tag                string   `json:"tag" form:"tag"`
	GoodsCarouselList  []string `json:"goodsCarouselList"`
}

type Response struct {
	ResultCode int         `json:"resultCode"`
	Msg        string      `json:"message"`
	Data       interface{} `json:"data"`
}

type SaveAddressRequest struct {
	UserName      string `json:"userName"`
	UserPhone     string `json:"userPhone"`
	DefaultFlag   int64  `json:"defaultFlag"` // 0-不是 1-是
	ProvinceName  string `json:"provinceName"`
	CityName      string `json:"cityName"`
	RegionName    string `json:"regionName"`
	DetailAddress string `json:"detailAddress"`
	Token         string `header:"token"`
}

type UpdateAddressRequest struct {
	AddressId     int64  `json:"addressId"`
	UserId        int64  `json:"userId, optional"`
	UserName      string `json:"userName"`
	UserPhone     string `json:"userPhone"`
	DefaultFlag   int64  `json:"defaultFlag"` // 0-不是 1-是
	ProvinceName  string `json:"provinceName"`
	CityName      string `json:"cityName"`
	RegionName    string `json:"regionName"`
	DetailAddress string `json:"detailAddress"`
	Token         string `header:"token"`
}

type DeleteAddressRequest struct {
	AddressId int64  `path:"addressId"`
	Token     string `header:"token"`
}

type GetMyAddressRequest struct {
	Token string `header:"token"`
}

type Address struct {
	AddressId     int64  `json:"addressId"`
	UserId        int64  `json:"userId"`
	UserName      string `json:"userName"`
	UserPhone     string `json:"userPhone"`
	DefaultFlag   int64  `json:"defaultFlag"`
	ProvinceName  string `json:"provinceN"`
	CityName      string `json:"cityName"`
	RegionName    string `json:"regionName"`
	DetailAddress string `json:"detailAddress"`
	IsDeleted     int64  `json:"isDeleted"`
	CreateTime    string `json:"createTime"`
	UpdateTime    string `json:"updateTime"`
}

type GetMyAddressResponse struct {
	AddressList []Address `json:"addressList"`
}

type GetAddressByIdRequest struct {
	AddressId int64  `path:"addressId"`
	Token     string `header:"token"`
}

type GetAddressByIdResponse struct {
	Address Address `json:"address"`
}

type GetDefaultAddressRequest struct {
	Token string `header:"token"`
}

type GetDefaultAddressResponse struct {
	Address Address `json:"address"`
}
