// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	LoginName   string `json:"loginName"`
	PasswordMd5 string `json:"passwordMd5"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type RegisterRequest struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type UpdateUserInfoRequest struct {
	Token         string `header:"token"`
	NickName      string `json:"nickName"`
	PasswordMd5   string `json:"passwordMd5"`
	IntroduceSign string `json:"introduceSign"`
}

type GetUserInfoRequest struct {
	Token string `header:"token"`
}

type GetUserInfoResponse struct {
	NickName      string `json:"nickName"`
	LoginName     string `json:"loginName"`
	IntroduceSign string `json:"introduceSign"`
}

type LogoutRequest struct {
	Token string `header:"token"`
}

type Response struct {
	ResultCode int         `json:"resultCode"`
	Msg        string      `json:"message"`
	Data       interface{} `json:"data"`
}
